### ISSUE TITLE
`grunt webpack --verbose` threw warning in multi-compiler situation

### ISSUE THREAD

**Issue by dickeylth** [webpack-contrib/grunt-webpack#122]
In multi-compiler situation (just from the [tests/fixtures/webpack/multi-compiler/](https://github.com/webpack-contrib/grunt-webpack/tree/master/tests/fixtures/webpack/multi-compiler)), when using `grunt` command with `--verbose`, the command will fail with wanring as shown below:

```
multi-compiler ➤ grunt webpack --verbose --stack                                                                                                                                                           git:master
Initializing
Command-line options: --verbose, --stack

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "/Users/hongshu/dev/github/grunt-webpack/tasks" tasks.
Loading "webpack-dev-server.js" tasks...OK
+ webpack-dev-server
Loading "webpack.js" tasks...OK
+ webpack
Loading "Gruntfile.js" tasks...OK
>> No tasks were registered or unregistered.

Running tasks: webpack

Running "webpack" task

Running "webpack:test" (webpack) task
Verifying property webpack.test exists in config...OK
Warning: pattern.indexOf is not a function Use --force to continue.
TypeError: pattern.indexOf is not a function
  at /Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/file.js:47:29
  at Array.forEach (native)
  at processPatterns (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/file.js:45:38)
  at Object.file.expand (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/file.js:102:17)
  at Object.fn [as src] (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/task.js:171:36)
  at /Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/task.js:190:24
  at Array.forEach (native)
  at Task.task.normalizeMultiTaskFiles (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/task.js:187:11)
  at Object.<anonymous> (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/task.js:246:23)
  at Object.thisTask.fn (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/grunt/task.js:73:16)
  at Object.<anonymous> (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/util/task.js:293:12)
  at /Users/hongshu/dev/github/grunt-webpack/node_modules/grunt/lib/util/task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:606:11)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3
```

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```json
{
  "your": { "config": "here" }
}
```

see: https://github.com/webpack-contrib/grunt-webpack/blob/master/tests/fixtures/webpack/multi-compiler/Gruntfile.js#L6

### Expected Behavior

No warning occurred.

### Current Behavior

Throwed a warning `Warning: pattern.indexOf is not a function`

### Possible Solution

Add support for switching webpack options from `target: [ webpackConfigA, webpackConfigB ]` value to `target:  { options: [ webpackConfigA, webpackConfigB ] }`

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 2.2.1
| grunt-webpack    | 2.0.1
| grunt            | 1.0.1
| node             |  6.9.5
| npm              |  3.10.10
| Operating System | darwin x64 16.4.0, macOS 10.12.3 (16D32)

**Comment by danez** [comment]
Thanks for creating the ticket in the grunt repository and for reporting here. 

I changed the way the config is loaded as proposed by @shama in #133. It needs some more work and a test, but can probably release it later today as 3.0.0-beta.2. 

I let you know when this happens.
