### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/grunt-webpack#164]
Cannot convert undefined or null to object.

```
Running "webpack" task
Warning: Cannot convert undefined or null to object Use --force to continue.
TypeError: Cannot convert undefined or null to object
  at Function.keys (<anonymous>:null:null)
  at Object.webpackTask (/Users/junger/dropbox/dev/test/node_modules/grunt-webpack/tasks/webpack.js:15:54)
  at Object.thisTask.fn (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/grunt/task.js:70:16)
  at Object.<anonymous> (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/util/task.js:294:30)
  at Task.runTaskFn (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/util/task.js:244:24)
  at Task.<anonymous> (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/util/task.js:293:12)
  at Task.start (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/util/task.js:302:5)
  at Object.grunt.tasks (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/grunt.js:155:8)
  at Object.module.exports [as cli] (/Users/junger/dropbox/dev/test/node_modules/grunt/lib/grunt/cli.js:27:9)
  at Object.<anonymous> (/Users/junger/dropbox/dev/test/node_modules/grunt-cli/bin/grunt:44:20)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (internal/modules/cjs/loader.js:589:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Module.require (internal/modules/cjs/loader.js:626:17)
  at require (internal/modules/cjs/helpers.js:20:18)
  at Object.<anonymous> (/Users/junger/dropbox/dev/test/node_modules/grunt/bin/grunt:3:1)
  at Module._compile (internal/modules/cjs/loader.js:678:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
  at Module.load (internal/modules/cjs/loader.js:589:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
  at Function.Module._load (internal/modules/cjs/loader.js:520:3)
  at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
  at startup (internal/bootstrap/node.js:228:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
```

### Webpack/Grunt Configuration (webpack.config.js, webpack part of Gruntfile.js)

```json
{
  "your": { "config": "here" }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| webpack          | 
| grunt-webpack    |
| grunt            |
| node             | 
| npm              | 
| Operating System |

**Comment by joshunger** [comment]
Thanks @danez 👍
