### ISSUE TITLE
Conflict with browser-sync-webpack-plugin?

### ISSUE THREAD

**Issue by dickeylth** [webpack-contrib/grunt-webpack#61]
Hi, I'm trying to combine [browser-sync-webpack-plugin](https://github.com/Va1/browser-sync-webpack-plugin#advanced) and grunt-webpack, here's my configuration:

```
'webpack-dev-server': {
      dev: {
        webpack: _.extend({}, webpackConfig, {
          plugins: [
            new webpack.HotModuleReplacementPlugin(),
            new LiveReloadPlugin(),
            new BrowserSyncPlugin(
              // BrowserSync options
              {
                // browse to http://localhost:3000/ during development
                host: 'localhost',
                port: 3000,
                // proxy the Webpack Dev Server endpoint
                // (which should be serving on http://localhost:3100/)
                // through BrowserSync
                proxy: 'http://localhost:8080/'
              },
              // plugin options
              {
                // prevent BrowserSync from reloading the page
                // and let Webpack Dev Server take care of this
                reload: false
              }
            )
          ]
        }),
        watch: true,
        keepalive: true,
        //hot: true,
        //inline: true
      }
    }
```

and with `grunt webpack-dev-server`, it throws an error:

```
Running "webpack-dev-server:dev" (webpack-dev-server) task
Warning: Circular reference detected (.webpack.plugins[2].browserSync.instance.publicInstance) Use --force to continue.
Error: Circular reference detected (.webpack.plugins[2].browserSync.instance.publicInstance)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:99:15)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
    at /Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:110:16
    at Array.map (native)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:109:20)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
    at recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:119:20)
    at Object.util.recurse (/Users/hongshu/dev/gitlab/v-tabs/node_modules/grunt/node_modules/grunt-legacy-util/index.js:130:10)

Aborted due to warnings.
```

Could you please provide any help? Thank you!

**Comment by olanb7** [comment]
Did you ever resolve this @dickeylth? I'm getting the same error now.

**Comment by latviancoder** [comment]
Getting the same error with the same plugin. @olanb7 solution didn't help.

**Comment by danez** [comment]
There will be a workaround in grunt-webpack 3.0.0 by wrapping the config into a callback.
see https://github.com/webpack-contrib/grunt-webpack#circular-reference-detected-plugins
